### ISSUE TITLE
Position Control Checklist

### ISSUE THREAD

**Issue by Ratoone** [RoboTeamTwente/roboteam_ai#813]
As the title says

- [x] Test Path Planning for multiple robots
- [x] Integration of Path Planning with the skills (GoToPos & InterfaceDrive) -> #776
- [x] Implement Defense Area [& Field] Collisions
- [ ] Nice to have: #784

**Comment by Ratoone** [comment]
Closed as the only relevant issue left is #784 and (not mandatory for now) the field collisions
