### ISSUE TITLE
Epic: Redesign Behaviour Tree Structure

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#814]
Centralized TODO list for the redesign of the behaviour trees. Brief: this restructure will improve the flexibility of our AI through a variety of plays being available for execution, make the structure clearer and removes certain hacks like DefaultTactic and RoleDivider. Additionally, the changes in this PR will enable the communication with the skills to be non-global

- [x] Get UML diagram vetted and approved by team

- [x] Build new role class according to UML

- [x] Build new skill class according to UML

- [x] Check dealer integration with role (test for pass)

- [ ] Add hysteresis to Play

- [ ] Make Play responsible for handling ref info and passing correct limitations down to tactics and skills

- [x] SkillInfo/TacticInfo 

- [x] Tactic class implemented
