### ISSUE TITLE
STP - continuation

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#996]
- [x] Play metrics #997 

- [x] Play invariants #998 

- [x] Pass determination

- [x]  Attacker positioning

- [x] Function to force plays (being worked on by Johan) in the interface for debugging purposes
- [x] More specialized plays

- [x] Make rule document

- [x] Referee protocol

- [x] What do we need to keep from the legacy code

- [x] Check if the class diagram and flow charts are up to date

- [x] Defender positioning

- [x] Keeper

- [x] Heavy algorithm daemon
